-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP SEQUENCE SEQ_PISTA_DE_AUDITORIA;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE QUINTA CASCADE CONSTRAINTS;

DROP TABLE PARCELA_AGRICOLA CASCADE CONSTRAINTS;

DROP TABLE CADERNO_DE_CAMPO CASCADE CONSTRAINTS;

DROP TABLE TIPO_DE_OPERACAO CASCADE CONSTRAINTS;

DROP TABLE OPERACAO CASCADE CONSTRAINTS;

DROP TABLE TIPO_DE_ALTERACAO CASCADE CONSTRAINTS;

DROP TABLE PISTA_DE_AUDITORIA CASCADE CONSTRAINTS;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE QUINTA (
    ID_QUINTA NUMBER(3) NOT NULL,
    CONSTRAINT PK_ID_QUINTA PRIMARY KEY (ID_QUINTA),
    CONSTRAINT CK_ID_QUINTA_POSITIVO CHECK (ID_QUINTA > 0)
);

CREATE TABLE PARCELA_AGRICOLA (
    ID_PARCELA_AGRICOLA NUMBER(3) NOT NULL,
    DESIGNACAO VARCHAR2(20) NOT NULL,
    AREA FLOAT(3) NOT NULL,
    ID_QUINTAQUINTA_PA NUMBER(3) NOT NULL,
    CONSTRAINT PK_ID_PARCELA_AGRICOLA PRIMARY KEY (ID_PARCELA_AGRICOLA),
    CONSTRAINT CK_ID_PARCELA_AGRICOLA_POSITIVO CHECK (ID_PARCELA_AGRICOLA > 0),
    CONSTRAINT CK_DESIGNACAO CHECK (REGEXP_LIKE(DESIGNACAO, '^[a-zA-Z ]*$')),
    CONSTRAINT CK_AREA_POSITIVO CHECK (AREA > 0)
);

CREATE TABLE CADERNO_DE_CAMPO (
    ID_CADERNO_DE_CAMPO NUMBER(10) NOT NULL,
    CONSTRAINT PK_ID_CADERNO_DE_CAMPO PRIMARY KEY (ID_CADERNO_DE_CAMPO),
    CONSTRAINT CK_ID_CADERNO_DE_CAMPO_POSITIVO CHECK (ID_CADERNO_DE_CAMPO > 0)
);

CREATE TABLE TIPO_DE_OPERACAO (
    ID_TIPO_DE_OPERACAO NUMBER(1) NOT NULL,
    DESCRICAO_DO_TIPO_DE_OPERACAO VARCHAR2(13) NOT NULL UNIQUE,
    CONSTRAINT PK_ID_TIPO_DE_OPERACAO PRIMARY KEY (ID_TIPO_DE_OPERACAO),
    CONSTRAINT CK_ID_TIPO_DE_OPERACAO_POSITIVO CHECK (ID_TIPO_DE_OPERACAO > 0),
    CONSTRAINT CK_DESCRICAO_DO_TIPO_DE_OPERACAO CHECK (REGEXP_LIKE(DESCRICAO_DO_TIPO_DE_OPERACAO, '^fertilizacao|sensor|colheita|rega$'))
);

CREATE TABLE OPERACAO (
    ID_OPERACAO NUMBER(10) NOT NULL,
    DATA_PLANEADA DATE NOT NULL,
    ID_CADERNO_DE_CAMPOCADERNO_DE_CAMPO NUMBER(10) NOT NULL,
    ID_TIPO_DE_OPERACAOTIPO_DE_OPERACAO NUMBER(1) NOT NULL,
    ID_PARCELA_AGRICOLAPARCELA_AGRICOLA_O NUMBER(3) NOT NULL,
    CONSTRAINT PK_ID_OPERACAO PRIMARY KEY (ID_OPERACAO),
    CONSTRAINT CK_ID_OPERACAO_POSITIVO CHECK (ID_OPERACAO > 0)
);

CREATE TABLE PISTA_DE_AUDITORIA (
    ID_PISTA_DE_AUDITORIA NUMBER(3) NOT NULL,
    UTILIZADOR VARCHAR2(15) NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    ID_OPERACAOOPERACAO_PA NUMBER(10) NOT NULL,
    ID_PARCELA_AGRICOLAPARCELA_AGRICOLA_PA NUMBER(3) NOT NULL,
    ID_TIPO_DE_ALTERACAOTIPO_DE_ALTERACAO NUMBER(1) NOT NULL,
    CONSTRAINT PK_ID_PISTA_DE_AUDITORIA PRIMARY KEY (ID_PISTA_DE_AUDITORIA),
    CONSTRAINT CK_ID_PISTA_DE_AUDITORIA_POSITIVO CHECK (ID_PISTA_DE_AUDITORIA > 0)
);

CREATE TABLE TIPO_DE_ALTERACAO (
    ID_TIPO_DE_ALTERACAO NUMBER(1) NOT NULL,
    DESCRICAO_DO_TIPO_DE_ALTERACAO VARCHAR2(6) NOT NULL UNIQUE,
    CONSTRAINT PK_ID_TIPO_DE_ALTERACAO PRIMARY KEY (ID_TIPO_DE_ALTERACAO),
    CONSTRAINT CK_ID_TIPO_DE_ALTERACAO_POSITIVO CHECK (ID_TIPO_DE_ALTERACAO > 0),
    CONSTRAINT CK_DESCRICAO_DO_TIPO_DE_ALTERACAO CHECK (REGEXP_LIKE(DESCRICAO_DO_TIPO_DE_ALTERACAO, '^UPDATE|INSERT|DELETE$'))
);

CREATE SEQUENCE SEQ_PISTA_DE_AUDITORIA START WITH 1 MINVALUE 1 INCREMENT BY 1 CACHE 100;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE PARCELA_AGRICOLA ADD CONSTRAINT FK_ID_QUINTAQUINTA_PA FOREIGN KEY (ID_QUINTAQUINTA_PA) REFERENCES QUINTA (ID_QUINTA);

ALTER TABLE OPERACAO ADD CONSTRAINT FK_ID_CADERNO_DE_CAMPOCADERNO_DE_CAMPO FOREIGN KEY (ID_CADERNO_DE_CAMPOCADERNO_DE_CAMPO) REFERENCES CADERNO_DE_CAMPO (ID_CADERNO_DE_CAMPO);

ALTER TABLE OPERACAO ADD CONSTRAINT FK_ID_TIPO_DE_OPERACAOTIPO_DE_OPERACAO FOREIGN KEY (ID_TIPO_DE_OPERACAOTIPO_DE_OPERACAO) REFERENCES TIPO_DE_OPERACAO (ID_TIPO_DE_OPERACAO);

ALTER TABLE OPERACAO ADD CONSTRAINT FK_ID_PARCELA_AGRICOLAPARCELA_AGRICOLA_O FOREIGN KEY (ID_PARCELA_AGRICOLAPARCELA_AGRICOLA_O) REFERENCES PARCELA_AGRICOLA (ID_PARCELA_AGRICOLA);

ALTER TABLE PISTA_DE_AUDITORIA ADD CONSTRAINT FK_ID_OPERACAOOPERACAO_PA FOREIGN KEY (ID_OPERACAOOPERACAO_PA) REFERENCES OPERACAO (ID_OPERACAO);

ALTER TABLE PISTA_DE_AUDITORIA ADD CONSTRAINT FK_ID_PARCELA_AGRICOLAPARCELA_AGRICOLA_PA FOREIGN KEY (ID_PARCELA_AGRICOLAPARCELA_AGRICOLA_PA) REFERENCES PARCELA_AGRICOLA (ID_PARCELA_AGRICOLA);

ALTER TABLE PISTA_DE_AUDITORIA ADD CONSTRAINT FK_ID_TIPO_DE_ALTERACAOTIPO_DE_ALTERACAO FOREIGN KEY (ID_TIPO_DE_ALTERACAOTIPO_DE_ALTERACAO) REFERENCES TIPO_DE_ALTERACAO (ID_TIPO_DE_ALTERACAO);