CREATE OR REPLACE FUNCTION GETSTRING (
    SOURCE_STRING IN VARCHAR2,
    FIELD_POSITION IN NUMBER,
    UNTERMINATED IN BOOLEAN DEFAULT FALSE,
    DELIMITER IN VARCHAR2 DEFAULT ','
) RETURN VARCHAR2 IS
    IPTREND         PLS_INTEGER := 0;
    IPTRSTART       PLS_INTEGER := 0;
    VCSOURCESTRCOPY VARCHAR2 (4000) := SOURCE_STRING;
BEGIN
    IF UNTERMINATED THEN
        VCSOURCESTRCOPY := VCSOURCESTRCOPY
            || DELIMITER;
    END IF;
    IF FIELD_POSITION > 1 THEN
        IPTRSTART := INSTR (VCSOURCESTRCOPY, DELIMITER, 1, FIELD_POSITION - 1) + LENGTH (DELIMITER);
    ELSE
        IPTRSTART := 1;
    END IF;
    IPTREND := INSTR (VCSOURCESTRCOPY, DELIMITER, 1, FIELD_POSITION);
    RETURN SUBSTR (VCSOURCESTRCOPY, IPTRSTART, (IPTREND - IPTRSTART));
END GETSTRING;