------------------PROCEDURE TO UPDATE A HUB IN A CLIENT ------------------------------
CREATE OR REPLACE PROCEDURE UPDATE_A_HUB_IN_A_CLIENT(
    NIF_TO_UPDATE IN CLIENTE.NIF%TYPE,
    HUB_TO_UPDATE IN CLIENTE.ID_HUB_DEFAULT%TYPE
) AS
BEGIN
    UPDATE CLIENTE
    SET
        ID_HUB_DEFAULT = HUB_TO_UPDATE
    WHERE
        NIF = NIF_TO_UPDATE;
    COMMIT;
END UPDATE_A_HUB_IN_A_CLIENT;
    /

CALL UPDATE_A_HUB_IN_A_CLIENT('298870017', 'CT10');

SELECT * FROM CLIENTE;