------------------PROCEDURE TO SET A HUB TO AN ORDER ------------------------------
create or replace PROCEDURE UPDATE_HUB_ENCOMENDA(
  L_ID_ENCOMENDA IN ENCOMENDA.ID_ENCOMENDA%TYPE,
  L_DATA_DA_ENCOMENDA IN ENCOMENDA.DATA_DA_ENCOMENDA%TYPE,
  L_VALOR IN ENCOMENDA.VALOR%TYPE,
  L_ID_ESTADO_DA_ENCOMENDAESTADO_DA_ENCOMENDA IN ENCOMENDA.ID_ESTADO_DA_ENCOMENDAESTADO_DA_ENCOMENDA%TYPE,
  L_ID_HUB IN ENCOMENDA.ID_HUB%TYPE,
  L_NIFCLIENTE IN ENCOMENDA.NIFCLIENTE%TYPE
) AS
  CURSOR CHECK_HUB_VALID IS
    SELECT
      LOC_ID
    FROM
      HUB;
  CHECK_HUB_VALID_ID HUB.LOC_ID%TYPE;
BEGIN
  OPEN CHECK_HUB_VALID;
  LOOP
    FETCH CHECK_HUB_VALID INTO CHECK_HUB_VALID_ID;
    EXIT WHEN CHECK_HUB_VALID%NOTFOUND;
    IF CHECK_HUB_VALID_ID = L_ID_HUB THEN
      INSERT INTO ENCOMENDA(
        ID_ENCOMENDA,
        DATA_DA_ENCOMENDA,
        VALOR,
        ID_ESTADO_DA_ENCOMENDAESTADO_DA_ENCOMENDA,
        ID_HUB,
        NIFCLIENTE
      ) VALUES (
        L_ID_ENCOMENDA,
        L_DATA_DA_ENCOMENDA,
        L_VALOR,
        L_ID_ESTADO_DA_ENCOMENDAESTADO_DA_ENCOMENDA,
        L_ID_HUB,
        L_NIFCLIENTE
      );
    END IF;
  END LOOP;
  COMMIT;
END;

CALL UPDATE_HUB_ENCOMENDA('4563524343', DATE'2022-10-25', 30, 1, 'CT11', '298870017');

SELECT * FROM ENCOMENDA;