------------------PROCEDURE TO INSERT A HUB IN A CLIENT BY DEFAULT ----------------------
create or replace PROCEDURE INSERT_HUB_BY_DEFAULT(
  L_NIF IN CLIENTE.NIF%TYPE,
  L_NOME IN CLIENTE.NOME%TYPE,
  L_EMAIL IN CLIENTE.EMAIL%TYPE,
  L_MORADA IN CLIENTE.MORADA%TYPE,
  L_ID_CLIENTEUTILIZADOR IN CLIENTE.ID_CLIENTEUTILIZADOR%TYPE,
  L_ID_TIPO_DE_CLIENTETIPO_DE_CLIENTE IN CLIENTE.ID_TIPO_DE_CLIENTETIPO_DE_CLIENTE%TYPE,
  L_ID_HUB_DEFAULT IN CLIENTE.ID_HUB_DEFAULT%TYPE
) IS
BEGIN
  INSERT INTO CLIENTE(
    NIF,
    NOME,
    EMAIL,
    MORADA,
    ID_CLIENTEUTILIZADOR,
    ID_TIPO_DE_CLIENTETIPO_DE_CLIENTE,
    ID_HUB_DEFAULT
  ) VALUES(
    L_NIF,
    L_NOME,
    L_EMAIL,
    L_MORADA,
    L_ID_CLIENTEUTILIZADOR,
    L_ID_TIPO_DE_CLIENTETIPO_DE_CLIENTE,
    L_ID_HUB_DEFAULT
  );
  COMMIT;
END;

CALL INSERT_HUB_BY_DEFAULT('298870017', 'Tiago', 'odric@hotmail.com', 'Morada', 1, 2, 'CT11');

SELECT
  *
FROM
  CLIENTE;